sources:
  - name: source_bronze
    database: realtime_dbt
    schema: bronze  
    tables:
      - name: trips

  - name: source_silver
    database: realtime_dbt
    schema: silver
    tables:
      - name: customers
      - name: locations
      - name: drivers
      - name: trips
      - name: payments
      - name: vehicles
